# docker-compose.yml
services:
  starship-1:
    build: .
    container_name: starship-1
    environment:
      - NODE_NAME=Starhip-1
      - NODE_PORT=5000
      - NEIGHBOR1_NAME=Satellite-1
      - NEIGHBOR1_PORT=5001
      - NEIGHBOR2_NAME=BaseStation-1
      - NEIGHBOR2_PORT=5002
    ports:
      - "5000:5000"
    networks:
      skynet:
        aliases:
          - node1

  satellite-1:
    build: .
    container_name: satellite-1
    environment:
      - NODE_NAME=Satellite-1
      - NODE_PORT=5001
      - NEIGHBOR1_NAME=Starship-1
      - NEIGHBOR1_PORT=5000
      - NEIGHBOR2_NAME=BaseStation-1
      - NEIGHBOR2_PORT=5002
    ports:
      - "5001:5001"
    networks:
      skynet:
        aliases:
          - node2

  basestation-1:
    build: .
    container_name: basestation-1
    environment:
      - NODE_NAME=BaseStation-1
      - NODE_PORT=5002
      - NEIGHBOR1_NAME=Starship-1
      - NEIGHBOR1_PORT=5000
      - NEIGHBOR2_NAME=Satellite-1
      - NEIGHBOR2_PORT=5001
    ports:
      - "5002:5002"
    networks:
      skynet:
        aliases:
          - node3

networks:
  skynet:
    driver: bridge

