# docker-compose.yml
version: '3.8'
services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_NAME=Node1
      - NODE_PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - log_volume:/app/logs
    networks:
      skynet:
        aliases:
          - node1

  node2:
    build: .
    container_name: node2
    environment:
      - NODE_NAME=Node2
      - NODE_PORT=5001
    ports:
      - "5001:5001"
    volumes:
      - log_volume:/app/logs
    networks:
      skynet:
        aliases:
          - node2

  node3:
    build: .
    container_name: node3
    environment:
      - NODE_NAME=Node3
      - NODE_PORT=5002
    ports:
      - "5002:5002"
    volumes:
      - log_volume:/app/logs
    networks:
      skynet:
        aliases:
          - node3

networks:
  skynet:
    driver: bridge

volumes:
  log_volume:
